<?php

namespace Database\Factories;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Service>
 */
class ServiceFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            //
        ];
    }

    public function withCustomData()
    {
        return [

            [
                'service_code' => '101',
                'name' => 'BVN Verification',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 100.00,
                'description' => 'BVN Verification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '102',
                'name' => 'Standard Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 50.00,
                'description' => 'BVN Standard Slip',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '103',
                'name' => 'BVN Premium Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 100.00,
                'description' => 'BVN Premium Slip FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '104',
                'name' => 'NIN Verification',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 150.00,
                'description' => 'NIN Verification fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '105',
                'name' => 'Regular NIN Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 50.00,
                'description' => 'Regular NIN Slip',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '106',
                'name' => 'Standard NIN Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 150.00,
                'description' => 'Standard NIN Slip',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '107',
                'name' => 'Premium NIN Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 200.00,
                'description' => 'Premium NIN Slip',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '108',
                'name' => 'NIN Personalization',
                'category' => 'Verifications',
                'type' => null,
                'amount' => 300.00,
                'description' => 'NIN Verification fee using tracking No',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '109',
                'name' => 'BVN Plastic ID',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 200.00,
                'description' => 'BVN Plastic ID FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '110',
                'name' => 'BVN Enrollment',
                'category' => 'Agency',
                'type' => 'Uncategorized',
                'amount' => 10000.00,
                'description' => 'BVN Enrollment FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '111',
                'name' => 'NIN Phone Verification',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 100.00,
                'description' => 'NIN Phone Verification FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '112',
                'name' => 'IPE Request',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 500.00,
                'description' => 'IPE Request FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '127',
                'name' => 'Basic NIN Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 50.00,
                'description' => 'Basic NIN Slip FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '128',
                'name' => 'NIN V2 Verification',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 150.00,
                'description' => 'NIN V2 Verification FEE',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => 'V101',
                'name' => 'VNIN Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 500.00,
                'description' => 'VNIN Slip Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '1111',
                'name' => 'Suspended NIN',
                'category' => 'Verifications',
                'type' => 'Suspended NIN',
                'amount' => 500.00,
                'description' => 'Suspended NIN Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => 'V1002',
                'name' => 'VNIN Verification Slip',
                'category' => 'Verifications',
                'type' => 'Uncategorized',
                'amount' => 150.00,
                'description' => 'VNIN Verification Slip Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '113',
                'name' => 'No Record Fund',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1000.00,
                'description' => 'No Record Fund Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '114',
                'name' => 'VNIN Validation',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1300.00,
                'description' => 'VNIN Validation Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '115',
                'name' => 'Validation for Immigration',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1300.00,
                'description' => 'Validation for Immigration Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '116',
                'name' => 'Photograph Error',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1300.00,
                'description' => 'Photograph Error Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '117',
                'name' => 'Modification Validation',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 2000.00,
                'description' => 'Modification Validation Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '118',
                'name' => 'Bypass NIN',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 100000.00,
                'description' => 'Bypass NIN Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '119',
                'name' => 'SIM Validation',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1300.00,
                'description' => 'SIM Validation Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '120',
                'name' => 'Internal Passport',
                'category' => 'Verifications',
                'type' => 'nin_services',
                'amount' => 1300.00,
                'description' => 'Internal Passport Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '129',
                'name' => 'Name Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 8000.00,
                'description' => 'Name Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '130',
                'name' => 'Date of Birth Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 45000.00,
                'description' => 'Date of Birth Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '131',
                'name' => 'Phone Number Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 8000.00,
                'description' => 'Phone Number Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '132',
                'name' => 'Address Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 8000.00,
                'description' => 'Address Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '133',
                'name' => 'Name and Date of Birth Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 50000.00,
                'description' => 'Name and Date of Birth Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '134',
                'name' => 'Phone Number and Date of Birth',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 50000.00,
                'description' => 'Phone Number and Date of Birth Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'service_code' => '135',
                'name' => 'Name and Phone Number Modification',
                'category' => 'Verifications',
                'type' => 'nin_mod',
                'amount' => 12000.00,
                'description' => 'Name and Phone Number Modification Fee',
                'status' => 'enabled',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];
    }
}
